### ISSUE TITLE
Video play gesture not working - drag release auto

### ISSUE THREAD

**Issue by corentin-begne** [ultraleap/TouchFree#341]
Hi,
I integrated the Sdk for the web and it works well but I have 2 issues.
- I can't play videos with sound and sounds, the needed gesture seems to be lost.
- I have a 360 scene where the user need to drag to move the camera, the drag release alone randomly eventif I don't change the depth of my hand.
Can you help me please ?

**Comment by cartmouse** [comment]
Hi there!

Happy to help you with these issues. To do that, I'll need a little more information about them.

1. I'm not entirely sure what you mean by the first point, could you send through a video of the issue and a code snippet if possible?
2. A video of this issue would be really helpful to understand the problem. It sounds like you are using the "Scroll and Drag" feature with the AirPush interaction here. If that is true, have you considered using the "Grab" interaction with this element? It might be better suited for this requirement.

**Comment by Craig-J** [comment]
This repository is being archived. If you still require assistance please email support@ultraleap.com or ask in the [Ultraleap developer discord](https://discord.gg/3VCndThqxS).
