### ISSUE TITLE
Cannot receive any HandData using TouchFree Tooling for Web

### ISSUE THREAD

**Issue by kqkq** [ultraleap/TouchFree#389]
The body of the `if` statement on https://github.com/ultraleap/TouchFree/blob/2eb874532f2d75b7b249214a107ce727bf73cc55/TF_Tooling_Web/src/Connection/ServiceConnection.ts#L124-L131 never be executed. I guess it means the TouchFree service didn't send any.

I didn't find any documentation on this. I am using TouchFree `2.4.0` binary release. Does this version support it? Should I enable some options to make it work?

Thank you so much!

**Comment by GabrielHomewoodUL** [comment]
Hi,
Currently the HandData returned here is not supported by the API, hence why there isn't documentation for it. The data returned is in a reference frame that is currently only used for our own debugging purposes. We will of course log your interest in provision of this data more officially.

**Comment by Craig-J** [comment]
This repository is being archived. If you still require assistance please emai support@ultraleap.com or ask in the [Ultraleap developer discord](https://discord.gg/3VCndThqxS).
